;; for S3 with 16MB flash, octal PSRAM, 
;; MOONHUB HUB75 adapter board
[env:esp32S3_16MB_PSRAM_M_HUB75]
extends = env:esp32S3_8MB_PSRAM_M
board = lilygo-t7-s3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

build_unflags = ${env:esp32S3_8MB_PSRAM_M.build_unflags}
  -D WLED_RELEASE_NAME=esp32S3_8MB_M
  -D LEDPIN=21
  ${Speed_Flags.build_unflags}  ;; to override -Os

build_flags = ${common.build_flags} ${esp32s3.build_flags} -Wno-misleading-indentation -Wno-format-truncation
  ${common_mm.build_flags_S} ${common_mm.build_flags_M}
  ${Speed_Flags.build_flags_V4}  ;; optimize for speed
  ${common_mm.HUB75_build_flags}
  -D MOONHUB_S3_PINOUT ;; HUB75 pinout
  ${common_mm.animartrix_build_flags}
  -D WLED_RELEASE_NAME=esp32S3_16MB_PSRAM_M_HUB75
  -D WLEDMM_FASTPATH
  -D WLED_DISABLE_BROWNOUT_DET
  ;; -D JSON_BUFFER_SIZE=18432 ;; default 54000
  -D MIN_HEAP_SIZE=6144      ;; default 8192
  -D MAX_SEGMENT_DATA=40960  ;; default 32767
  -DBOARD_HAS_PSRAM ;; -D WLED_USE_PSRAM ;; your board supports PSRAM
  -D WLED_USE_PSRAM_JSON -DALL_JSON_TO_PSRAM ; WLEDMM --> force all JSON stuff into PSRAM; gives more free heap
  -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=0 -DARDUINO_USB_MSC_ON_BOOT=0 -DARDUINO_USB_DFU_ON_BOOT=0     ;; for Serial-to-USB chip
  ;; -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MSC_ON_BOOT=0 -DARDUINO_USB_DFU_ON_BOOT=1   ;; for Hardware-CDC USB mode
  -D WLED_WATCHDOG_TIMEOUT=0 -D CONFIG_ASYNC_TCP_USE_WDT=0
  ;; -DUSERMOD_BATTERY_MEASUREMENT_PIN=2  ;; battery voltage pin
  ;; -D STATUSLED=17 ;; onboard LED
  -D LEDPIN=14 -D BTNPIN=0 -D RLYPIN=15 -D IRPIN=-1 -D AUDIOPIN=-1 ;; defaults that avoid pin conflicts with HUB75
  -D SR_DMTYPE=1 -D I2S_SDPIN=10 -D I2S_CKPIN=11 -D I2S_WSPIN=12 -D MCLK_PIN=-1  ;; I2S mic

lib_deps = ${esp32s3.lib_deps} ${common_mm.lib_deps_S}  ${common_mm.lib_deps_V4_M}
    ${common_mm.HUB75_lib_deps}
    ${common_mm.animartrix_lib_deps}
;lib_ignore = IRremoteESP8266 ; use with WLED_DISABLE_INFRARED for faster compilation

board_build.partitions = ${esp32.extreme_partitions}
board_upload.flash_size = 16MB
board_upload.maximum_size =16777216
; RAM:   [==        ]  19.0% (used 62332 bytes from 327680 bytes)
; Flash: [======    ]  57.7% (used 1813585 bytes from 3145728 bytes)